const surahData = [
  { "number": 1, "name": "Al-Fatiha", "englishName": "The Opening", "ayats": 7 },
  { "number": 2, "name": "Al-Baqarah", "englishName": "The Cow", "ayats": 286 },
  { "number": 3, "name": "Al-Imran", "englishName": "Family of Imran", "ayats": 200 },
  { "number": 4, "name": "An-Nisa", "englishName": "The Women", "ayats": 176 },
  { "number": 5, "name": "Al-Ma'idah", "englishName": "The Table Spread", "ayats": 120 },
  { "number": 6, "name": "Al-An'am", "englishName": "The Cattle", "ayats": 165 },
  { "number": 7, "name": "Al-A'raf", "englishName": "The Heights", "ayats": 206 },
  { "number": 8, "name": "Al-Anfal", "englishName": "The Spoils of War", "ayats": 75 },
  { "number": 9, "name": "At-Taubah", "englishName": "The Repentance", "ayats": 129 },
  { "number": 10, "name": "Yunus", "englishName": "Jonah", "ayats": 109 },
  { "number": 11, "name": "Hud", "englishName": "Hud", "ayats": 123 },
  { "number": 12, "name": "Yusuf", "englishName": "Joseph", "ayats": 111 },
  { "number": 13, "name": "Ar-Ra'd", "englishName": "Thunder", "ayats": 43 },
  { "number": 14, "name": "Ibrahim", "englishName": "Abraham", "ayats": 52 },
  { "number": 15, "name": "Al-Hijr", "englishName": "The Stoneland", "ayats": 99 },
  { "number": 16, "name": "An-Nahl", "englishName": "The Bee", "ayats": 128 },
  { "number": 17, "name": "Al-Isra", "englishName": "The Night Journey", "ayats": 111 },
  { "number": 18, "name": "Al-Kahf", "englishName": "The Cave", "ayats": 110 },
  { "number": 19, "name": "Maryam", "englishName": "Mary", "ayats": 98 },
  { "number": 20, "name": "Ta-Ha", "englishName": "Ta-Ha", "ayats": 135 },
  { "number": 21, "name": "Al-Anbiya", "englishName": "The Prophets", "ayats": 112 },
  { "number": 22, "name": "Al-Hajj", "englishName": "The Pilgrimage", "ayats": 78 },
  { "number": 23, "name": "Al-Mu'minun", "englishName": "The Believers", "ayats": 118 },
  { "number": 24, "name": "An-Nur", "englishName": "The Light", "ayats": 64 },
  { "number": 25, "name": "Al-Furqan", "englishName": "The Criterion", "ayats": 77 },
  { "number": 26, "name": "Ash-Shu'ara", "englishName": "The Poets", "ayats": 227 },
  { "number": 27, "name": "An-Naml", "englishName": "The Ants", "ayats": 93 },
  { "number": 28, "name": "Al-Qasas", "englishName": "The Story", "ayats": 88 },
  { "number": 29, "name": "Al-'Ankabut", "englishName": "The Spider", "ayats": 69 },
  { "number": 30, "name": "Ar-Rum", "englishName": "The Romans", "ayats": 60 },
  { "number": 31, "name": "Luqman", "englishName": "Luqman", "ayats": 34 },
  { "number": 32, "name": "As-Sajdah", "englishName": "The Prostration", "ayats": 30 },
  { "number": 33, "name": "Al-Ahzab", "englishName": "The Confederates", "ayats": 73 },
  { "number": 34, "name": "Saba", "englishName": "Sheba", "ayats": 54 },
  { "number": 35, "name": "Fatir", "englishName": "The Originator", "ayats": 45 },
  { "number": 36, "name": "Ya-Sin", "englishName": "Ya Sin", "ayats": 83 },
  { "number": 37, "name": "As-Saffat", "englishName": "Those who set the Ranks", "ayats": 182 },
  { "number": 38, "name": "Sad", "englishName": "Sad", "ayats": 88 },
  { "number": 39, "name": "Az-Zumar", "englishName": "The Troops", "ayats": 75 },
  { "number": 40, "name": "Ghafir", "englishName": "The Forgiver", "ayats": 85 },
  { "number": 41, "name": "Fussilat", "englishName": "Explained in Detail", "ayats": 54 },
  { "number": 42, "name": "Ash-Shura", "englishName": "The Consultation", "ayats": 53 },
  { "number": 43, "name": "Az-Zukhruf", "englishName": "The Ornaments of Gold", "ayats": 89 },
  { "number": 44, "name": "Ad-Dukhan", "englishName": "The Smoke", "ayats": 59 },
  { "number": 45, "name": "Al-Jathiyah", "englishName": "The Kneeling", "ayats": 36 },
  { "number": 46, "name": "Al-Ahqaf", "englishName": "The Sand Dunes", "ayats": 35 },
  { "number": 47, "name": "Muhammad", "englishName": "Muhammad", "ayats": 38 },
  { "number": 48, "name": "Al-Fath", "englishName": "The Victory", "ayats": 29 },
  { "number": 49, "name": "Al-Hujurat", "englishName": "The Rooms", "ayats": 18 },
  { "number": 50, "name": "Qaf", "englishName": "Qaf", "ayats": 45 },
  { "number": 51, "name": "Adh-Dhariyat", "englishName": "The Winnowing Winds", "ayats": 60 },
  { "number": 52, "name": "At-Tur", "englishName": "The Mount", "ayats": 49 },
  { "number": 53, "name": "An-Najm", "englishName": "The Star", "ayats": 62 },
  { "number": 54, "name": "Al-Qamar", "englishName": "The Moon", "ayats": 55 },
  { "number": 55, "name": "Ar-Rahman", "englishName": "The Beneficent", "ayats": 78 },
  { "number": 56, "name": "Al-Waqi'ah", "englishName": "The Inevitable", "ayats": 96 },
  { "number": 57, "name": "Al-Hadid", "englishName": "The Iron", "ayats": 29 },
  { "number": 58, "name": "Al-Mujadila", "englishName": "The Pleading Woman", "ayats": 22 },
  { "number": 59, "name": "Al-Hashr", "englishName": "The Exile", "ayats": 24 },
  { "number": 60, "name": "Al-Mumtahanah", "englishName": "She That Is To Be Examined", "ayats": 13 },
  { "number": 61, "name": "As-Saff", "englishName": "The Ranks", "ayats": 14 },
  { "number": 62, "name": "Al-Jumu'ah", "englishName": "The Congregation (Friday)", "ayats": 11 },
  { "number": 63, "name": "Al-Munafiqun", "englishName": "The Hypocrites", "ayats": 11 },
  { "number": 64, "name": "At-Taghabun", "englishName": "The Mutual Disillusion", "ayats": 18 },
  { "number": 65, "name": "At-Talaq", "englishName": "The Divorce", "ayats": 12 },
  { "number": 66, "name": "At-Tahrim", "englishName": "The Prohibiting", "ayats": 12 },
  { "number": 67, "name": "Al-Mulk", "englishName": "The Sovereignty", "ayats": 30 },
  { "number": 68, "name": "Al-Qalam", "englishName": "The Pen", "ayats": 52 },
  { "number": 69, "name": "Al-Haqqah", "englishName": "The Inevitable", "ayats": 52 },
  { "number": 70, "name": "Al-Ma'arij", "englishName": "The Ascending Stairways", "ayats": 44 },
  { "number": 71, "name": "Nuh", "englishName": "Noah", "ayats": 28 },
  { "number": 72, "name": "Al-Jinn", "englishName": "The Jinn", "ayats": 28 },
  { "number": 73, "name": "Al-Muzzammil", "englishName": "The Enshrouded One", "ayats": 20 },
  { "number": 74, "name": "Al-Muddaththir", "englishName": "The Cloaked One", "ayats": 56 },
  { "number": 75, "name": "Al-Qiyamah", "englishName": "The Resurrection", "ayats": 40 },
  { "number": 76, "name": "Al-Insan", "englishName": "The Man", "ayats": 31 },
  { "number": 77, "name": "Al-Mursalat", "englishName": "The Emissaries", "ayats": 50 },
  { "number": 78, "name": "An-Naba", "englishName": "The Tidings", "ayats": 40 },
  { "number": 79, "name": "An-Nazi'at", "englishName": "Those Who Drag Forth", "ayats": 46 },
  { "number": 80, "name": "Abasa", "englishName": "He Frowned", "ayats": 42 },
  { "number": 81, "name": "At-Takwir", "englishName": "The Overthrowing", "ayats": 29 },
  { "number": 82, "name": "Al-Infitar", "englishName": "The Cleaving", "ayats": 19 },
  { "number": 83, "name": "Al-Mutaffifin", "englishName": "The Defrauding", "ayats": 36 },
  { "number": 84, "name": "Al-Inshiqaq", "englishName": "The Sundering", "ayats": 25 },
  { "number": 85, "name": "Al-Buruj", "englishName": "The Mansions of the Stars", "ayats": 22 },
  { "number": 86, "name": "At-Tariq", "englishName": "The Night-Comer", "ayats": 17 },
  { "number": 87, "name": "Al-A'la", "englishName": "The Most High", "ayats": 19 },
  { "number": 88, "name": "Al-Ghashiyah", "englishName": "The Overwhelming", "ayats": 26 },
  { "number": 89, "name": "Al-Fajr", "englishName": "The Dawn", "ayats": 30 },
  { "number": 90, "name": "Al-Balad", "englishName": "The City", "ayats": 20 },
  { "number": 91, "name": "Ash-Shams", "englishName": "The Sun", "ayats": 15 },
  { "number": 92, "name": "Al-Layl", "englishName": "The Night", "ayats": 21 },
  { "number": 93, "name": "Ad-Duha", "englishName": "The Morning Hours", "ayats": 11 },
  { "number": 94, "name": "Ash-Sharh", "englishName": "The Consolation", "ayats": 8 },
  { "number": 95, "name": "At-Tin", "englishName": "The Fig", "ayats": 8 },
  { "number": 96, "name": "Al-'Alaq", "englishName": "The Clot", "ayats": 19 },
  { "number": 97, "name": "Al-Qadr", "englishName": "The Power, Fate", "ayats": 5 },
  { "number": 98, "name": "Al-Bayyinah", "englishName": "The Clear Proof", "ayats": 8 },
  { "number": 99, "name": "Az-Zalzalah", "englishName": "The Earthquake", "ayats": 8 },
  { "number": 100, "name": "Al-'Adiyat", "englishName": "The Courser", "ayats": 11 },
  { "number": 101, "name": "Al-Qari'ah", "englishName": "The Calamity", "ayats": 11 },
  { "number": 102, "name": "At-Takathur", "englishName": "The Rivalry in Worldly Increase", "ayats": 8 },
  { "number": 103, "name": "Al-'Asr", "englishName": "The Declining Day, Eventide", "ayats": 3 },
  { "number": 104, "name": "Al-Humazah", "englishName": "The Traducer", "ayats": 9 },
  { "number": 105, "name": "Al-Fil", "englishName": "The Elephant", "ayats": 5 },
  { "number": 106, "name": "Quraish", "englishName": "Quraish", "ayats": 4 },
  { "number": 107, "name": "Al-Ma'un", "englishName": "The Small Kindnesses", "ayats": 7 },
  { "number": 108, "name": "Al-Kawthar", "englishName": "The Abundance", "ayats": 3 },
  { "number": 109, "name": "Al-Kafirun", "englishName": "The Disbelievers", "ayats": 6 },
  { "number": 110, "name": "An-Nasr", "englishName": "The Divine Support", "ayats": 3 },
  { "number": 111, "name": "Al-Masad", "englishName": "The Palm Fiber", "ayats": 5 },
  { "number": 112, "name": "Al-Ikhlas", "englishName": "The Sincerity", "ayats": 4 },
  { "number": 113, "name": "Al-Falaq", "englishName": "The Daybreak", "ayats": 5 },
  { "number": 114, "name": "An-Nas", "englishName": "Mankind", "ayats": 6 }
];

export default surahData;
